version: '2'
services:
    postgis:
        image: geofabrik/docker-postgis
        volumes:
            # place your *.osm files here
            - ./import:/data/import:ro
        expose:
            - 5432
    apatir:
        image: geofabrik/docker-apache-tirex
        links:
            - postgis
        entrypoint: ./wait-for-postgres.sh postgis /usr/local/bin/start.sh
        volumes:
            # place your tile gz files here e.g. osm0-12.gz and osmbright0-12.gz
            - ./osm:/data/osm
            # here the extracted files will be placed
            - ./osmbright:/var/lib/tirex/tiles/osmbright
            - ./osmcarto:/var/lib/tirex/tiles/osmcarto
        expose:
            - 80
        ports:
            - "8081:80"
